# Generated by Django 4.1.1 on 2022-10-08 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_stock',
            field=models.BooleanField(default=True),
        ),
    ]
