# Generated by Django 4.1.1 on 2022-10-08 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_is_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_code',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
