# Generated by Django 4.1.1 on 2022-10-08 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_product_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.TextField(max_length=255, null=True, unique=True),
        ),
    ]
